Build non-concurrent to avoid random build error
See https://ci.appveyor.com/project/emgarten/sleet/builds/35055181#L315:

```
C:\projects\sleet\.cli\sdk\3.1.101\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3088: Could not read state file "C:\projects\sleet\artifacts\proj\SleetLib\obj\Release\netstandard2.0\SleetLib.csprojAssemblyReference.cache". The process cannot access the file 'C:\projects\sleet\artifacts\proj\SleetLib\obj\Release\netstandard2.0\SleetLib.csprojAssemblyReference.cache' because it is being used by another process. [C:\projects\sleet\src\SleetLib\SleetLib.csproj]
  SleetLib -> C:\projects\sleet\artifacts\proj\SleetLib\bin\Release\netstandard2.0\SleetLib.dll
CSC : error CS2012: Cannot open 'C:\projects\sleet\artifacts\proj\SleetLib\obj\Release\netstandard2.0\SleetLib.dll' for writing -- 'The process cannot access the file 'C:\projects\sleet\artifacts\proj\SleetLib\obj\Release\netstandard2.0\SleetLib.dll' because it is being used by another process.' [C:\projects\sleet\src\SleetLib\SleetLib.csproj]
```

Which totally looks like a concurrency issue.